### ISSUE TITLE
Building example in conda environment

### ISSUE THREAD

**Issue by mihsamusev** [bast/pybind11-demo#2]
Hi, thanks for your work. I would like to run the code in conda environment that has different python version (3.7) than my base environment (3.8). I follow the example building and reaching the `cmake ..` step i get this:

```
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so (found version "3.8.2") 
-- Found PythonInterp: /home/msa/anaconda3/envs/pybind11_demo/bin/python3.7 (found version "3.7.9") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- pybind11 v2.3.dev0
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
-- Configuring done
-- Generating done
-- Build files have been written to: /home/msa/Documents/repos/pybind11-demo/build
```
So it already looks like `PythonLibs` and `PythonInterp` are found for different versions of python. Finishing the build with `make` i obtain `example.cpython-37m-x86_64-linux-gnu.so`. Testing it with `python -c "import example"` gives the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: Python version mismatch: module was compiled for version 3.8, while the interpreter is running version 3.7.
```

What should i change (perhaps in `CMakeLists.txt`) to be able to build this for my conda environment? I found a [solution](https://github.com/pybind/cmake_example) that gives a complicated `setup.py` that nevertheless works, but for my own understanding id like a minimal example. Thanks in advance.

**Comment by bast** [comment]
Can you try whether this fixes it: https://github.com/dev-cafe/cmake-cookbook/blob/e2cdfb3c79477014966d893e9712b27aa18048b3/chapter-03/recipe-02/c-example/CMakeLists.txt#L12?

If yes, please let me know and then I will adapt also this repo (right now not enough time to test it myself).

**Comment by mihsamusev** [comment]
Thanks a lot, changing this line 
https://github.com/bast/pybind11-demo/blob/93e4e7c4e715f1a02f2ab42bc4f10b3bbc43a6cb/CMakeLists.txt#L4
to
```
find_package(PythonInterp REQUIRED)
```
Solves the error of python version mismatch. `cmake` finds matching interpreter and library paths. 
```
...
-- Found PythonInterp: /home/msa/anaconda3/envs/pybind11_demo/bin/python (found version "3.7.9") 
-- Found PythonLibs: /home/msa/anaconda3/envs/pybind11_demo/lib/libpython3.7m.so
...
```

**Comment by bast** [comment]
Great! Re-opening, just that I don't forget to fix the example.
